---
# ansible_playbook_infra_ovirt/collections/requirements.yml
# Author: MTO
# Description: Collections requirements.yml for host
#
 collections:
  - name: ovirt.ovirt
    version: 1.3.0
    source: https://galaxy.ansible.com

  - name: ansible.posix
