---
# ansible_playbook_infra_ovirt/playbooks/ovirt_info.yml
# Author: MTO
# Description: ovirt_info.yml file for ansible_playbook_infra_ovirt
#
- name: "OVIRT_INFO"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "OVIRT_INFO: Obtain info"
      block:
        - name: "OVIRT_INFO - Include Vars"
          ansible.builtin.include_vars: 
            file: ../vars/ovirt_password.yml

        - name: "OVIRT_INFO - Obtain SSO token with using username/password credentials."
          ovirt.ovirt.ovirt_auth:
            url: https://ovirt-engine.mto.local/ovirt-engine/api
            username: admin@internal
            ca_file: ca.pem
            password: "{{ ovirt_password }}"

        - name: "OVIRT_INFO : Obtain Datacenter info"
          ovirt.ovirt.ovirt_datacenter_info:
            pattern: name=Default*
            register: result
        
        - ansible.builtin.debug:
            msg: "{{ result.ovirt_datacenters }}"
    
      always:
        - name: "OVIRT_INFO: Always revoke the SSO token"
          ovirt.ovirt.ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
